project:
  type: website

website:
  title: "weblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: mastodon
        href: https://fosstodon.org
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual
execute:
  freeze: auto
