project:
  type: website

website:
  title: "fm weblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/feinmann 
      - icon: mastodon
        href: https://fosstodon.org/@feinmann 
format:
  html:
    theme: darkly
    css: styles.css

editor: visual
execute:
  freeze: auto
